apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgress
    author: vishva
spec:
 containers:
   - name: mydb
     image: postgres
     env:
      - name: POSTGRES_PASSWORD
        value: vishva
      - name: POSTGRES_USER
        value: user
      - name: POSTGRES_DB
        value: mydb
     ports:
       - containerPort: 5432
...