---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    author: vishva
spec:
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    name: redis
    author: vishva
...




