---
apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
   name: result-app
   author: vishva
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 90
...