---
apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app
    author: vishva
spec:
  containers:
    - name: worker-app
      image: dockersamples/examplevotingapp_worker

...